apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctf-deployment
  labels:
    app: suctf-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: suctf-app
  template:
    metadata:
      labels:
        app: suctf-app
    spec:
      securityContext:
        runAsUser: 1001
      containers:
        - name: vuln-container
          image: cloudenv/python-playground:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "1200Mi"
              cpu: "700m"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: suctf-svc
spec:
  type: NodePort
  selector:
    app: suctf-app
  ports:
    - protocol: TCP
      port: 5000
      nodePort: 30080
