apiVersion: batch/v1
kind: CronJob
metadata:
  name: restarter
spec:
  schedule: "01 * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          serviceAccountName: job-runner
          automountServiceAccountToken: true
          containers:
            - name: kubectl-delete-pod
              image: bitnami/kubectl
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - export TOKEN=`cat /var/run/secrets/kubernetes.io/serviceaccount/token`; /opt/bitnami/kubectl/bin/kubectl --token=${TOKEN} --server=https://${KUBERNETES_PORT_443_TCP_ADDR}:443 --insecure-skip-tls-verify=true rollout restart deployment ctf-deployment
          restartPolicy: OnFailure
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: delete-pods-role
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: delete-pods-binding
subjects:
  - kind: ServiceAccount
    name: job-runner
roleRef:
  kind: Role
  name: delete-pods-role
  apiGroup: rbac.authorization.k8s.io
