version: "3.2"

services:
  web:
    container_name: shahname
    restart: on-failure
    build: 
      context: ./src/web
      dockerfile: Dockerfile
    ports:
      - 1337:1337
    environment:
      - PORT=1337

  bot:
    container_name: visit_bot
    restart: on-failure
    build: 
      context: ./src/bot
      dockerfile: Dockerfile
    ports:
      - 1336:1336
    environment:
      - FLAG=FMCTF{fake_flag}
      - PORT=1336
