#used to setup the http server that helped with generating the pcap
from python
copy KaB-proof-of-concept.py KaB_Doc.pdf steg.png key /home/
workdir /home/
cmd ["python3", "-m", "http.server", "-b", "0.0.0.0", "80"]
