services:
  bot:
    build: ./bot/
    restart: always 
    ports:
      - "8001:8000"
    environment:
      - "FLAG=FMCTF{f266b251865bb2627f945165a12598aa}"
      - "CAPTCHA_SECRET="
      - "WEB_DOMAIN=web"
  web:
    image: nginx:latest
    restart: always 
    ports:
      - "8000:80"
    volumes:
      - ./chall.html:/usr/share/nginx/html/index.html
